---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kerjadekat
  source:
    repoURL: https://github.com/YOUR_ORG/kerjadekat
    targetRevision: HEAD
    path: gitops/base/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: kerjadekat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
