---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kerjadekat
  source:
    repoURL: https://helm.elastic.co
    targetRevision: 8.5.1
    chart: elasticsearch
    helm:
      values: |
        replicas: 1
        minimumMasterNodes: 1
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi
        volumeClaimTemplate:
          resources:
            requests:
              storage: 5Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
