# gitops/overlays/aks-lite/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/backend
  - ../../base/frontend
  - ../../base/infra

patches:
  - path: patches/backend-loadbalancer.yaml
  - path: patches/frontend-loadbalancer.yaml
  - path: patches/storage-class-pg.yaml
  - path: patches/hpa-backend-limit.yaml
  - path: patches/hpa-frontend-limit.yaml

images:
  - name: kerjadekat/postgres-postgis
    newName: ghalitsar/kerjadekat-postgres-postgis
    newTag: "17-3.5"
  # Backend & frontend tidak perlu direplace karena memang sudah dari dockerhub ghalitsar di base

configMapGenerator:
  - name: kerjadekat-backend-config
    namespace: kerjadekat
    behavior: merge
    literals:
      - ENV=production
      - DB_SSLMODE=require
      # Fallback ke public RabbitMQ & Redis (atau ngrok tunnel lokal Anda)
      - RABBITMQ_URL="amqp://guest:guest@localhost:5672/" 
      - REDIS_HOST="localhost"
