---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kerjadekat-frontend-hpa
  namespace: kerjadekat
  labels:
    app: kerjadekat-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kerjadekat-frontend
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
