apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: kerjadekat
type: Opaque
stringData:
  DB_PASSWORD: "kerjadekat_pass"
  DB_USER: "kerjadekat"
  DB_NAME: "kerjadekat"
  JWT_SECRET: "eks-deploy-jwt-secret-kerjadekat-2026"
  XENDIT_API_KEY: "xnd_development_GfvVBCm9GACVDJrvi7cOCIGDB1BvnPTxzK23AbhSgaZJTquZYR0Tv54eezA815"
  XENDIT_CALLBACK_TOKEN: "sQVJ6uLGk45DU8OpdfQjW6qnNaFws0YvbgjZ0N1J2eFnmouZ"
