apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: kerjadekat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghalitsar/kerjadekat-frontend:8b4f45b
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: VITE_API_BASE_URL
              value: "/api/v1"
            - name: KERJADEKAT_API_BASE
              value: "http://backend-svc.kerjadekat.svc.cluster.local:8085/api/v1"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: kerjadekat
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: frontend
