---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kerjadekat
  namespace: argocd
spec:
  description: "KerjaDekat Platform Services"
  sourceRepos:
    - "*"
  destinations:
    - namespace: kerjadekat
      server: https://kubernetes.default.svc
    - namespace: kerjadekat-infra
      server: https://kubernetes.default.svc
    - namespace: kong
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: logging
      server: https://kubernetes.default.svc
    - namespace: jenkins
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
