---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kerjadekat
  source:
    repoURL: https://github.com/ghalitsar-coder/kerjadekat-gitops
    targetRevision: HEAD
    path: gitops/argocd/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy: {}
    # automated sync disabled for local dev (Minikube)
    # syncPolicy:
    #   automated:
    #     prune: true
    #     selfHeal: true
