---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-application-aks-lite
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kerjadekat
  source:
    repoURL: https://github.com/ghalitsar-coder/kerjadekat-gitops
    targetRevision: HEAD
    path: gitops/overlays/aks-lite
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
